einride/spanner-aip-go

- internal/codegen/tablecodegen/interleavedreadtransaction_test.go
- internal/codegen/tablecodegen/interleavedrow.go
- internal/codegen/tablecodegen/interleavedrow_test.go
- internal/codegen/tablecodegen/interleavedrowiterator_test.go
- internal/codegen/tablecodegen/partialkey.go
- internal/codegen/tablecodegen/primarykey.go
- internal/codegen/tablecodegen/row.go
- internal/codegen/tablecodegen/testdata/1.sql.interleavedreadtransaction.go
- internal/codegen/tablecodegen/testdata/1.sql.interleavedrow.go
- internal/codegen/tablecodegen/testdata/1.sql.interleavedrowiterator.go
- internal/codegen/tablecodegen/testdata/1.sql.keyrange.go
- internal/codegen/tablecodegen/testdata/1.sql.partialkey.go
- internal/codegen/tablecodegen/testdata/1.sql.primarykey.go
- internal/codegen/tablecodegen/testdata/1.sql.readtransaction.go
- internal/codegen/tablecodegen/testdata/1.sql.row.go
- internal/codegen/tablecodegen/testdata/1.sql.rowiterator.go
- internal/codegen/tablecodegen/testdata/2.sql.interleavedreadtransaction.go
- internal/codegen/tablecodegen/testdata/2.sql.interleavedrow.go
- internal/codegen/tablecodegen/testdata/2.sql.interleavedrowiterator.go
- internal/codegen/tablecodegen/testdata/2.sql.keyrange.go
- internal/codegen/tablecodegen/testdata/2.sql.partialkey.go
- internal/codegen/tablecodegen/testdata/2.sql.primarykey.go
- internal/codegen/tablecodegen/testdata/2.sql.readtransaction.go
- internal/codegen/tablecodegen/testdata/2.sql.row.go
- internal/codegen/tablecodegen/testdata/2.sql.rowiterator.go
- internal/examples/freightdb/tables_gen.go
- internal/examples/musicdb/tables_gen.go
All types of mutations for basic rows.
Insert, Update and InsertOrUpdate for interleaved rows.
Delete mutation for interleaved rows will use a specific key type for
interleaved rows that can generate a primary key delete for the
top-level table and key prefix deletes for interleaved tables.
> feat: code generate mutations

- internal/codegen/databasecodegen/database.go
- internal/codegen/databasecodegen/interleavedreadtransaction.go
- internal/codegen/databasecodegen/interleavedrow.go
- internal/codegen/databasecodegen/interleavedrowiterator.go
- spanddl/database.go
- spanddl/database_test.go
- spanddl/table.go
To aid code generation of multiple levels of interleaved tables.
Interleaved tables can be discovered by traversing the hierarchy from
the top-level table.
> feat: add InterleavedTables field to spanddl.Table

- aip-spanner-go.yaml
- cmd/aip-spanner-go/main.go
- go.mod
- internal/config/codegeneration.go
- internal/config/database.go
- internal/config/doc.go
- internal/protoloader/loader.go
- internal/protoloader/loader_test.go
Loads the package-level file descriptor set during runtime for
configurable proto messages.
To be used for code generation of protobuf/Spanner data conversion, and
a protobuf-first query API.
> feat: add protoloader package

- internal/codegen/descriptorcodegen/table.go
- internal/codegen/descriptorcodegen/testdata/1.sql.database.go
- internal/codegen/descriptorcodegen/testdata/1.sql.table.go
- internal/codegen/descriptorcodegen/testdata/2.sql.database.go
- internal/codegen/descriptorcodegen/testdata/2.sql.table.go
- internal/examples/freightdb/descriptor_gen.go
- internal/examples/musicdb/descriptor_gen.go
Struct has the implementation but the interface is missing the
declaration, so it's not accessible via the public API.
> fix: add missing ColumnExprs method to table descriptor

- internal/codegen/databasecodegen/readtransaction.go
- internal/codegen/databasecodegen/testdata/2.sql.database.go
- internal/codegen/databasecodegen/testdata/3.sql.database.go
- internal/codegen/databasecodegen/testdata/4.sql.database.go
- internal/codegen/databasecodegen/testdata/6.sql
- internal/codegen/databasecodegen/testdata/6.sql.database.go
- internal/examples/freightdb/database_gen.go
- internal/examples/freightdb/database_test.go
- internal/examples/musicdb/database_gen.go
- testdata/migrations/freight/000003_shipments.up.sql
If an interleaved table has a delete time, the `ShowDeleted` option will
apply also to interleaved tables.
> fix: hide deleted interleaved rows by default

- internal/codegen/databasecodegen/readtransaction.go
- internal/codegen/databasecodegen/testdata/6.sql.database.go
- internal/examples/freightdb/database_gen.go
- internal/examples/freightdb/database_test.go
This behavior aligns more closely to AIP 164 (Soft Deletes).
See: https://google.aip.dev/164
> Get (AIP-131) requests for soft-deleted resources should return the
> resource (rather than a NOT_FOUND error).
> fix: return deleted results for interleaved Get/BatchGet

- internal/codegen/databasecodegen/key.go
- internal/codegen/databasecodegen/readtransaction.go
- internal/codegen/databasecodegen/testdata/1.sql.database.go
- internal/codegen/databasecodegen/testdata/2.sql.database.go
- internal/codegen/databasecodegen/testdata/3.sql.database.go
- internal/codegen/databasecodegen/testdata/4.sql.database.go
- internal/codegen/databasecodegen/testdata/5.sql.database.go
- internal/codegen/databasecodegen/testdata/6.sql.database.go
- internal/codegen/databasecodegen/testdata/7.sql.database.go
- internal/examples/freightdb/database_gen.go
- internal/examples/musicdb/database_gen.go
Comparing NULL values in Spanner does not work with regular `=` but
needs `IS NULL` comparator.
When listing interleaved table, using `a = b` when both a and b are NULL
returns a falsy value (`NULL`) leading to no rows returned.
> fix: handle nullable primary key in query API

- doc.go
- spanordering/doc.go
- spanordering/transpile.go
- spanordering/transpile_test.go
For naming parity between the following packages:
* `spanordering` (to transpile ordering.OrderBy to Spanner SQL)
* `spanfiltering` (to transpile filtering.Filter to Spanner SQL)
BREAKING CHANGE: aipspansql.Order package has been renamed to
spanordering.TranspileOrderBy.
> feat: rename aipspansql to spanordering

- spanfiltering/transpile_test.go
- spanfiltering/transpiler.go
Empty filters are transpiled to TRUE.
> feat(spanfiltering): handle empty filters

- spanfiltering/transpile.go
- spanfiltering/transpile_test.go
- spanfiltering/transpiler.go
Instead of transpiling filters to a single spansql.BoolExpr with
spansql.[...]Literal, filters are transpiled to a spansql.BoolExpr with
every literal returned as a parameter.
This fixes potential security issue where malicous filters are
transpiled directly to SQL without proper escaping.
Parameters are automatically named using a counter based on order of
appearance in the expr.Expr AST. This could be prettier, but atleast
provides a deterministic naming which *could* improve ability to cache
the filter (this is an assumption).
> feat!: transpile filters to expressions with parameters

- internal/examples/freightdb/database_test.go
- internal/examples/musicdb/database_test.go
- spantest/emulator.go
- spantest/fixture.go
- spantest/inmemory.go
To make it easier to migrate tests to-and-from using the Dockerized
emulator.
> feat(spantest): add InMemoryFixture with API-parity to emulator fixture

- spanfiltering/transpile_test.go
- spanfiltering/transpiler.go
Implements a subset of the recommended `has` interpretations described
in https://google.aip.dev/160#has-operator.
> feat: transpile has operator on repeated primitives

- internal/codegen/databasecodegen/row.go
- internal/codegen/databasecodegen/testdata/1.sql.database.go
- internal/codegen/databasecodegen/testdata/2.sql.database.go
- internal/codegen/databasecodegen/testdata/3.sql.database.go
- internal/codegen/databasecodegen/testdata/4.sql.database.go
- internal/codegen/databasecodegen/testdata/5.sql.database.go
- internal/codegen/databasecodegen/testdata/6.sql.database.go
- internal/codegen/databasecodegen/testdata/7.sql.database.go
- internal/examples/freightdb/database_gen.go
- internal/examples/musicdb/database_gen.go
Context:
Spanner has a hard limit on size of a mutation that is 20k cells, the
product of rows and columns. Schemas for protobuf messages containing
oneofs could be mapped to large number of nullable fields in Spanner.
When inserting rows to this schema, the majority of these nullable
fields will not be set, and setting the column to null is equivalent to
not setting it at all. This method, not setting columns at all,
drastically lowers the number of cells mutated in a mutation.
---
This change adds `row.MutatePresentColumns` which only mutates nullable
fields that are present.
* Nullable scalars are considered present if `column.Valid == true`
* Nullable arrays are considered present if `len(column) != 0`
* Nullable bytes are considered present if `len(colum) != 0`
> feat: add MutatePresentColumns method

- .golangci.yml
- go.mod
- go.sum
- internal/protoloader/loader.go
- spantest/emulator.go
- tools/golangci-lint/rules.mk
IPv6 support in Docker may result in multiple host/port combinations.
This ensures deterministic selection of the first pair.
> feat: select first host/port of emulator

- spantest/emulator.go
- spantest/fixture.go
- spantest/inmemory.go
- feat(spantest): support multiple schema globs
- fix(spantest): use grpc.WithBlock to dial emulator
> spantest: quality of life fixes

- go.mod
- internal/codegen/databasecodegen/readtransaction.go
- internal/codegen/databasecodegen/testdata/6.sql.database.go
- internal/examples/freightdb/database_gen.go
- internal/examples/freightdb/database_test.go
This is too hard to get right for all use cases. The simplest thing to
reason about is to only consider soft deletes for the top-level table
(because that's the one that determines pagination) and let the caller
filter out interleaved results as required.
BREAKING CHANGE: Soft-deleted interleaved rows will now always be
returned.
> feat: don't consider soft delete for interleaved rows

- .github/workflows/ci.yml
This is to prevent CI from bumping go version by itself.
Minor versions will still be automatically bumped.
> chore(ci): pin go 1.16

- go.mod
- go.sum
- spanfiltering/transpile_test.go
- spanfiltering/transpiler.go
Previously we were missing the option to transpile not equals to spansql. This PR adds that support﻿
> feat(enums): add support to transpile not equals functions

- internal/codegen/databasecodegen/readtransaction.go
- internal/codegen/databasecodegen/testdata/2.sql.database.go
- internal/codegen/databasecodegen/testdata/3.sql.database.go
- internal/codegen/databasecodegen/testdata/4.sql.database.go
- internal/codegen/databasecodegen/testdata/6.sql.database.go
- internal/examples/freightdb/database_gen.go
- internal/examples/musicdb/database_gen.go
If the user attempts to call a generated List method without supplying a key (with the purpose of returning the entire table), we get an empty slice as a reply if no data exists in the database.
If the same is done on a table which has a interleaved child and the user asks for interleaved data by setting the RowsQuery field to true, we attempt to perform a query on the interleaved table without having a key to perform such a query (since there is no data returned from the parent List) and we get back an `Unimplemented` error from the spanner library with the error message `Cloud Spanner does not support reading no keys`.
This fix makes it so that if the list query returned no keys, we do not query the interleaved child table and just return an empty slice
> feat: do not run interleaved queries with empty keys

- internal/codegen/typescodegen/types.go
- internal/examples/freightdb/database_gen.go
- internal/examples/freightdb/descriptor_gen.go
- testdata/migrations/freight/000002_sites.up.sql
Currently doesn't support JSON and we cannot generate code if a spanner column has the JSON type. 
This fix adds JSON support and ensures that we can have columns with the JSON type.
> feat: add json support

- spantest/emulator.go
To decrease waiting for the container to be reported as ready, as today we could be waiting an extra second before our tests run.
> feat(spantest): decrease sleep duration from 1 second to 100 milliseconds

- internal/codegen/databasecodegen/goldenfile_test.go
- internal/codegen/descriptorcodegen/goldenfile_test.go
- internal/config/database.go
- internal/protoloader/loader.go
- main.go
- spanddl/database_example_test.go
- spantest/emulator.go
- spantest/fixture.go
- spantest/inmemory.go
Change all functions to take `testing.TB` instead of `*testing.T` as
arguments.
This makes it possible to provide `*testing.B` for benchmark tests, and
`*testing.F` for fuzz tests.
@odsod @ericwenn as this changes the interface, should we consider this a breaking change? `testing.TB` is more limited than `*testing.T`, but all usages in this package is covered by `testing.TB` so I don't think it is a breaking change. But I could introduce a separate interface 🤷
> feat(spantest): support bench and fuzz tests

- spantest/emulator.go
Set SPANNER_EMULATOR_SKIP_PULL to avoid pulling the spantest image
before launching. This makes it possible to run the tests without
internet connectivity.
> feat(spantest): support offline mode

- go.mod
- go.sum
- internal/codegen/databasecodegen/readtransaction.go
- internal/codegen/databasecodegen/testdata/2.sql.database.go
- internal/codegen/databasecodegen/testdata/3.sql.database.go
- internal/codegen/databasecodegen/testdata/4.sql.database.go
- internal/codegen/databasecodegen/testdata/6.sql.database.go
- internal/examples/freightdb/database_gen.go
- internal/examples/musicdb/database_gen.go
Reads on interleaved tables are not dependent and can be read in
parallel. This increases throughput when reading a table including more
than one interleaved table.
---
- refactor(databasegen): make interleaved table reads independent
- perf(databasegen): perform reads on interleaved tables in parallell
> perf(databasegen): read interleaved tables in parallel

- internal/examples/musicdb/database_gen.go
- internal/examples/musicdb/descriptor_gen.go
- spanddl/table.go
- testdata/migrations/music/000001_music.up.sql
This PR makes it so that the `applyDropConstraintAlteration` and `applyAddConstraintAlteration` no longer return errors, thus allowing us to add `CONSTRAINT`s to already existing tables. The code generation does not seem to use `CONSTRAINT`s in any way, so this change should be valid. Furthermore, it makes it more consistent with `applyCreateTable`, since that function also does not take `CONSTRAINT`s into account.
> fix: don't return error on alter constraint

- .github/workflows/release.yml
seems like `--rm-dist `flag has been deprecated. Changing to `--clean` as suggested by error message here:
https://github.com/einride/spanner-aip-go/actions/runs/5485997803/jobs/9995506253
> fix: replace go release deprecaded --rm-dist

- spanddl/database.go
- spanddl/database_test.go
- testdata/migrations/music/000002_create_drop_genres.up.sql
- test(spanddl): possibility to specify expected error for ddl statement
- feat: throw error if dropping table with interleaved tables
- fix(spanddl): support dropping interleaved tables
> fix(spanddl): support dropping interleaved tables

- spanfiltering/transpile_test.go
- spanfiltering/transpiler.go
According to the filtering BNFC spec, using the "=" operator with an RHS
starting or ending with "*" should be evaluated as substring matching.
> feat: add support for substring matching

- spantest/emulator.go
Having some CI issues in a repo using this, so in order to simplify debugging this PR adds some extra info to the nil error assertions done when setting up the instance and client in the emulator.
> feat: add assert nilErr messages
